import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const gilroy = localFont({
  src: '../fonts/gilroy/Gilroy-Regular.ttf',
  display: 'swap'
});

export const metadata: Metadata = {
  title: 'Nimcure App | Home',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${gilroy.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
