export const PatientInformation = [
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Oluwaseun',
    LastName: 'Aregbesola',
    Email: 'Oluwaseunaregbesola@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Paid',
    DeliveryStatus: 'Delivered',
    Location: 'VI, Lagos',
    Status: 'Completed'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Stella',
    LastName: 'Omotoye',
    Email: 'Stella.omotoye@gmail.com',
    Gender: 'Female',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Paid',
    DeliveryStatus: 'Delivered',
    Location: 'VI, Lagos',
    Status: 'Completed'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Chinyere',
    LastName: 'Okafor',
    Email: 'Chinyere.okafor@gmail.com',
    Gender: 'Female',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Due & Paid',
    DeliveryStatus: 'Pending',
    Location: 'VI, Lagos',
    Status: 'Due & Paid'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Mohammed',
    LastName: 'Danladi',
    Email: 'Mohammed.danladi@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Due & Unpaid',
    DeliveryStatus: 'Pending',
    Location: 'VI, Lagos',
    Status: 'Due & Unpaid'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Michael',
    LastName: 'Aribisala',
    Email: 'Michael.aribisala@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Pending',
    DeliveryStatus: 'Assigned',
    Location: 'VI, Lagos',
    Status: 'Assigned'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Donatus',
    LastName: 'Emefiele',
    Email: 'Donatus.emefiele@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Pending',
    DeliveryStatus: 'Assigned',
    Location: 'VI, Lagos',
    Status: 'Assigned'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Donatus',
    LastName: 'Emefiele',
    Email: 'Donatus.emefiele@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Paid',
    DeliveryStatus: 'Delivered',
    Location: 'VI, Lagos',
    Status: 'Completed'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Donatus',
    LastName: 'Emefiele',
    Email: 'Donatus.emefiele@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Due & Paid',
    DeliveryStatus: 'Pending',
    Location: 'VI, Lagos',
    Status: 'Due & Paid'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Donatus',
    LastName: 'Emefiele',
    Email: 'Donatus.emefiele@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Due & Unpaid',
    DeliveryStatus: 'Pending',
    Location: 'VI, Lagos',
    Status: 'Due & Unpaid'
  },
  {
    HospitalID: '1AFHFH093',
    FirstName: 'Donatus',
    LastName: 'Emefiele',
    Email: 'Donatus.emefiele@gmail.com',
    Gender: 'Male',
    PhoneNumber: '+2347068642920',
    DeliveryDate: '2020-09-12',
    DeliveryTime: '12:00',
    DeliveryAddress: 'VI, Lagos',
    PaymentStatus: 'Paid',
    DeliveryStatus: 'Delivered',
    Location: 'VI, Lagos',
    Status: 'Paid'
  }
];
